package com.blm.qiubopay.models;

import java.util.ArrayList;
import java.util.List;

public class QPAY_CountryAndStates {

    public static List<String> getCountries(){
        List<String> listItems = new ArrayList<String>();

        listItems.add("AFGHANISTAN");
        listItems.add("ALAND ISLANDS");
        listItems.add("ALBANIA");
        listItems.add("ALGERIA");
        listItems.add("AMERICAN SAMOA");
        listItems.add("ANDORRA");
        listItems.add("ANGOLA");
        listItems.add("ANGUILLA");
        listItems.add("ANTARCTICA");
        listItems.add("ANTIGUA AND BARBUDA");
        listItems.add("ARGENTINA");
        listItems.add("ARMENIA");
        listItems.add("ARUBA");
        listItems.add("AUSTRALIA");
        listItems.add("AUSTRIA");
        listItems.add("AZERBAIJAN");
        listItems.add("BAHAMAS");
        listItems.add("BAHRAIN");
        listItems.add("BANGLADESH");
        listItems.add("BARBADOS");
        listItems.add("BELARUS");
        listItems.add("BELGIUM");
        listItems.add("BELIZE");
        listItems.add("BENIN");
        listItems.add("BERMUDA");
        listItems.add("BHUTAN");
        listItems.add("BOLIVIA, PLURINATIONAL STATE OF");
        listItems.add("BONAIRE, SINT EUSTATIUS AND SABA");
        listItems.add("BOSNIA AND HERZEGOVINA");
        listItems.add("BOTSWANA");
        listItems.add("BOUVET ISLAND");
        listItems.add("BRAZIL");
        listItems.add("BRITISH INDIAN OCEAN TERRITORY");
        listItems.add("BRUNEI DARUSSALAM");
        listItems.add("BULGARIA");
        listItems.add("BURKINA FASO");
        listItems.add("BURUNDI");
        listItems.add("CAMBODIA");
        listItems.add("CAMEROON");
        listItems.add("CANADA");
        listItems.add("CAPE VERDE");
        listItems.add("CAYMAN ISLANDS");
        listItems.add("CENTRAL AFRICAN REPUBLIC");
        listItems.add("CHAD");
        listItems.add("CHILE");
        listItems.add("CHINA");
        listItems.add("CHRISTMAS ISLAND");
        listItems.add("COCOS (KEELING) ISLANDS");
        listItems.add("COLOMBIA");
        listItems.add("COMOROS");
        listItems.add("CONGO");
        listItems.add("CONGO, THE DEMOCRATIC REPUBLIC OF THE");
        listItems.add("COOK ISLANDS");
        listItems.add("COSTA RICA");
        listItems.add("CÔTE D''IVOIRE");
        listItems.add("CROATIA");
        listItems.add("CUBA");
        listItems.add("CURAÇAO");
        listItems.add("CYPRUS");
        listItems.add("CZECH REPUBLIC");
        listItems.add("DENMARK");
        listItems.add("DJIBOUTI");
        listItems.add("DOMINICA");
        listItems.add("DOMINICAN REPUBLIC");
        listItems.add("ECUADOR");
        listItems.add("EGYPT");
        listItems.add("EL SALVADOR");
        listItems.add("EQUATORIAL GUINEA");
        listItems.add("ERITREA");
        listItems.add("ESTONIA");
        listItems.add("ETHIOPIA");
        listItems.add("FALKLAND ISLANDS (MALVINAS)");
        listItems.add("FAROE ISLANDS");
        listItems.add("FIJI");
        listItems.add("FINLAND");
        listItems.add("FRANCE");
        listItems.add("FRENCH GUIANA");
        listItems.add("FRENCH POLYNESIA");
        listItems.add("FRENCH SOUTHERN TERRITORIES");
        listItems.add("GABON");
        listItems.add("GAMBIA");
        listItems.add("GEORGIA");
        listItems.add("GERMANY");
        listItems.add("GHANA");
        listItems.add("GIBRALTAR");
        listItems.add("GREECE");
        listItems.add("GREENLAND");
        listItems.add("GRENADA");
        listItems.add("GUADELOUPE");
        listItems.add("GUAM");
        listItems.add("GUATEMALA");
        listItems.add("GUERNSEY");
        listItems.add("GUINEA");
        listItems.add("GUINEA-BISSAU");
        listItems.add("GUYANA");
        listItems.add("HAITI");
        listItems.add("HEARD ISLAND AND MCDONALD ISLANDS");
        listItems.add("HOLY SEE (VATICAN CITY STATE)");
        listItems.add("HONDURAS");
        listItems.add("HONG KONG");
        listItems.add("HUNGARY");
        listItems.add("ICELAND");
        listItems.add("INDIA");
        listItems.add("INDONESIA");
        listItems.add("IRAN, ISLAMIC REPUBLIC OF");
        listItems.add("IRAQ");
        listItems.add("IRELAND");
        listItems.add("ISLE OF MAN");
        listItems.add("ISRAEL");
        listItems.add("ITALY");
        listItems.add("JAMAICA");
        listItems.add("JAPAN");
        listItems.add("JERSEY");
        listItems.add("JORDAN");
        listItems.add("KAZAKHSTAN");
        listItems.add("KENYA");
        listItems.add("KIRIBATI");
        listItems.add("KOREA, DEMOCRATIC PEOPLE''S REPUBLIC OF");
        listItems.add("KOREA, REPUBLIC OF");
        listItems.add("KUWAIT");
        listItems.add("KYRGYZSTAN");
        listItems.add("LAO PEOPLE''S DEMOCRATIC REPUBLIC");
        listItems.add("LATVIA");
        listItems.add("LEBANON");
        listItems.add("LESOTHO");
        listItems.add("LIBERIA");
        listItems.add("LIBYA");
        listItems.add("LIECHTENSTEIN");
        listItems.add("LITHUANIA");
        listItems.add("LUXEMBOURG");
        listItems.add("MACAO");
        listItems.add("MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF");
        listItems.add("MADAGASCAR");
        listItems.add("MALAWI");
        listItems.add("MALAYSIA");
        listItems.add("MALDIVES");
        listItems.add("MALI");
        listItems.add("MALTA");
        listItems.add("MARSHALL ISLANDS");
        listItems.add("MARTINIQUE");
        listItems.add("MAURITANIA");
        listItems.add("MAURITIUS");
        listItems.add("MAYOTTE");
        listItems.add("MEXICO");
        listItems.add("MICRONESIA, FEDERATED STATES OF");
        listItems.add("MOLDOVA, REPUBLIC OF");
        listItems.add("MONACO");
        listItems.add("MONGOLIA");
        listItems.add("MONTENEGRO");
        listItems.add("MONTSERRAT");
        listItems.add("MOROCCO");
        listItems.add("MOZAMBIQUE");
        listItems.add("MYANMAR");
        listItems.add("NAMIBIA");
        listItems.add("NAURU");
        listItems.add("NEPAL");
        listItems.add("NETHERLANDS");
        listItems.add("NEW CALEDONIA");
        listItems.add("NEW ZEALAND");
        listItems.add("NICARAGUA");
        listItems.add("NIGER");
        listItems.add("NIGERIA");
        listItems.add("NIUE");
        listItems.add("NORFOLK ISLAND");
        listItems.add("NORTHERN MARIANA ISLANDS");
        listItems.add("NORWAY");
        listItems.add("OMAN");
        listItems.add("PAKISTAN");
        listItems.add("PALAU");
        listItems.add("PALESTINE, STATE OF");
        listItems.add("PANAMA");
        listItems.add("PAPUA NEW GUINEA");
        listItems.add("PARAGUAY");
        listItems.add("PERU");
        listItems.add("PHILIPPINES");
        listItems.add("PITCAIRN");
        listItems.add("POLAND");
        listItems.add("PORTUGAL");
        listItems.add("PUERTO RICO");
        listItems.add("QATAR");
        listItems.add("RÉUNION");
        listItems.add("ROMANIA");
        listItems.add("RUSSIAN FEDERATION");
        listItems.add("RWANDA");
        listItems.add("SAINT BARTHÉLEMY");
        listItems.add("SAINT HELENA, ASCENSION AND TRISTAN DA CUNHA");
        listItems.add("SAINT KITTS AND NEVIS");
        listItems.add("SAINT LUCIA");
        listItems.add("SAINT MARTIN (FRENCH PART)");
        listItems.add("SAINT PIERRE AND MIQUELON");
        listItems.add("SAINT VINCENT AND THE GRENADINES");
        listItems.add("SAMOA");
        listItems.add("SAN MARINO");
        listItems.add("SAO TOME AND PRINCIPE");
        listItems.add("SAUDI ARABIA");
        listItems.add("SENEGAL");
        listItems.add("SERBIA");
        listItems.add("SEYCHELLES");
        listItems.add("SIERRA LEONE");
        listItems.add("SINGAPORE");
        listItems.add("SINT MAARTEN (DUTCH PART)");
        listItems.add("SLOVAKIA");
        listItems.add("SLOVENIA");
        listItems.add("SOLOMON ISLANDS");
        listItems.add("SOMALIA");
        listItems.add("SOUTH AFRICA");
        listItems.add("SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS");
        listItems.add("SOUTH SUDAN");
        listItems.add("SPAIN");
        listItems.add("SRI LANKA");
        listItems.add("SUDAN");
        listItems.add("SURINAME");
        listItems.add("SVALBARD AND JAN MAYEN");
        listItems.add("SWAZILAND");
        listItems.add("SWEDEN");
        listItems.add("SWITZERLAND");
        listItems.add("SYRIAN ARAB REPUBLIC");
        listItems.add("TAIWAN, PROVINCE OF CHINA");
        listItems.add("TAJIKISTAN");
        listItems.add("TANZANIA, UNITED REPUBLIC OF");
        listItems.add("THAILAND");
        listItems.add("TIMOR-LESTE");
        listItems.add("TOGO");
        listItems.add("TOKELAU");
        listItems.add("TONGA");
        listItems.add("TRINIDAD AND TOBAGO");
        listItems.add("TUNISIA");
        listItems.add("TURKEY");
        listItems.add("TURKMENISTAN");
        listItems.add("TURKS AND CAICOS ISLANDS");
        listItems.add("TUVALU");
        listItems.add("UGANDA");
        listItems.add("UKRAINE");
        listItems.add("UNITED ARAB EMIRATES");
        listItems.add("UNITED KINGDOM");
        listItems.add("UNITED STATES");
        listItems.add("UNITED STATES MINOR OUTLYING ISLANDS");
        listItems.add("URUGUAY");
        listItems.add("UZBEKISTAN");
        listItems.add("VANUATU");
        listItems.add("VENEZUELA, BOLIVARIAN REPUBLIC OF");
        listItems.add("VIET NAM");
        listItems.add("VIRGIN ISLANDS, BRITISH");
        listItems.add("VIRGIN ISLANDS, U.S.");
        listItems.add("WALLIS AND FUTUNA");
        listItems.add("WESTERN SAHARA");
        listItems.add("YEMEN");
        listItems.add("ZAMBIA");
        listItems.add("ZIMBABWE");


        return listItems;
    }

    public static List<String> getStates(){
        List<String> listItems = new ArrayList<String>();

        listItems.add("Aguascalientes");
        listItems.add("Baja California");
        listItems.add("Baja California Sur");
        listItems.add("Campeche");
        listItems.add("Chiapas");
        listItems.add("Chihuahua");
        listItems.add("Coahuila de Zaragoza");
        listItems.add("Colima");
        listItems.add("Ciudad de Mexico");
        listItems.add("Durango");
        listItems.add("Guanajuato");
        listItems.add("Guerrero");
        listItems.add("Hidalgo");
        listItems.add("Jalisco");
        listItems.add("Estado de Mexico");
        listItems.add("Michoacan de Ocampo");
        listItems.add("Morelos");
        listItems.add("Nayarit");
        listItems.add("Nuevo Leon");
        listItems.add("Oaxaca");
        listItems.add("Puebla");
        listItems.add("Queretaro");
        listItems.add("Quintana Roo");
        listItems.add("San Luis Potosi");
        listItems.add("Sinaloa");
        listItems.add("Sonora");
        listItems.add("Tabasco");
        listItems.add("Tamaulipas");
        listItems.add("Tlaxcala");
        listItems.add("Veracruz");
        listItems.add("Yucatan");
        listItems.add("Zacatecas");

        return listItems;
    }
}
